language: generic
sudo: required
services:
  - docker

before_install:
  - docker build it shaheermir/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shaheermir/docker-react npm run test -- --coverage
