FROM node:alpine

WORKDIR '/app'
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .
RUN npm install

# in dev mode, we dont really need to copy over everything like we are doing here.
# thats because we already use mounts to reference this folder from inside the container.
COPY . .

CMD ["npm", "start"]
